#ifndef EXPERIMENTAL_USERS_AGL_LIBSLEEVI_FILLINS_NET_ERRORS_H
#define EXPERIMENTAL_USERS_AGL_LIBSLEEVI_FILLINS_NET_ERRORS_H

namespace bssl {

enum Error {
  OK = 0,
};

}  // namespace bssl

#endif  // EXPERIMENTAL_USERS_AGL_LIBSLEEVI_FILLINS_NET_ERRORS_H
