/* Copyright (c) 2016, Google Inc.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. */

/* This file was generated by generate_built_in_curves.go. */

#include <openssl/ec.h>

#include <openssl/bn.h>
#include <openssl/nid.h>

#include "../bn/internal.h"
#include "internal.h"


const EC_GROUP *EC_p224(void) {
  static const BN_ULONG kField[] = {
      TOBN(0x00000000, 0x00000001),
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xffffffff, 0xffffffff),
      0xffffffff,
  };

  static const BN_ULONG kOrder[] = {
      TOBN(0x13dd2945, 0x5c5c2a3d),
      TOBN(0xffff16a2, 0xe0b8f03e),
      TOBN(0xffffffff, 0xffffffff),
      0xffffffff,
  };

#if defined(EC_P224_NO_MONTGOMERY)

  static const BN_ULONG kA[] = {
      TOBN(0xffffffff, 0xfffffffe),
      TOBN(0xfffffffe, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      0xffffffff,
  };

  static const BN_ULONG kB[] = {
      TOBN(0x270b3943, 0x2355ffb4),
      TOBN(0x5044b0b7, 0xd7bfd8ba),
      TOBN(0x0c04b3ab, 0xf5413256),
      0xb4050a85,
  };

  static const BN_ULONG kX[] = {
      TOBN(0x343280d6, 0x115c1d21),
      TOBN(0x4a03c1d3, 0x56c21122),
      TOBN(0x6bb4bf7f, 0x321390b9),
      0xb70e0cbd,
  };

  static const BN_ULONG kY[] = {
      TOBN(0x44d58199, 0x85007e34),
      TOBN(0xcd4375a0, 0x5a074764),
      TOBN(0xb5f723fb, 0x4c22dfe6),
      0xbd376388,
  };

  static const BN_ULONG kOne[] = {
      0x00000001,
  };

#else /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0x00000000, 0x00000001),
      TOBN(0xfffffffe, 0x00000000),
      TOBN(0xffffffff, 0xffffffff),
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {0xffffffff, 0xffffffff}
  };

  static const BN_ULONG kA[] = {
      TOBN(0x00000000, 0x00000004),
      TOBN(0xfffffffc, 0x00000000),
      TOBN(0xffffffff, 0xffffffff),
      0xffffffff,
  };

  static const BN_ULONG kB[] = {
      TOBN(0xccf01310, 0xe768cdf7),
      TOBN(0xc8528150, 0x743b1cc0),
      TOBN(0x7fc02f93, 0x3dceba98),
      0x9c3fa633,
  };

  static const BN_ULONG kX[] = {
      TOBN(0x6018bfaa, 0xbc905227),
      TOBN(0xf96bec04, 0xf22fe220),
      TOBN(0xa21b5e60, 0x6dd3af9b),
      0x92f5b516,
  };

  static const BN_ULONG kY[] = {
      TOBN(0x05335a6b, 0x2edca1e6),
      TOBN(0x03dfe878, 0xe8c15513),
      TOBN(0x614786f1, 0xaea9c5ae),
      0x100c1218,
  };

  static const BN_ULONG kOne[] = {
      TOBN(0xffffffff, 0xffffffff),
      0xffffffff,
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0xffffffff, 0x00000001),
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xfffffffe, 0x00000000),
      0xffffffff,
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {UINT64_C(0xffffffffffffffff), 0}
  };

  static const BN_ULONG kA[] = {
      TOBN(0x00000003, 0x00000001),
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xffffffff, 0xfffffffc),
      0xffffffff,
  };

  static const BN_ULONG kB[] = {
      TOBN(0xe768cdf6, 0x63c059cd),
      TOBN(0x107ac2f3, 0xccf01310),
      TOBN(0x3dceba98, 0xc8528151),
      0x7fc02f93,
  };

  static const BN_ULONG kX[] = {
      TOBN(0xbc905226, 0x6d0a4aea),
      TOBN(0x85259736, 0x6018bfaa),
      TOBN(0x6dd3af9b, 0xf96bec05),
      0xa21b5e60,
  };

  static const BN_ULONG kY[] = {
      TOBN(0x2edca1e5, 0xeff3ede8),
      TOBN(0xf8cd672b, 0x05335a6b),
      TOBN(0xaea9c5ae, 0x03dfe878),
      0x614786f1,
  };

  static const BN_ULONG kOne[] = {
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xffffffff, 0xffffffff),
  };

#endif /* BN_BITS2 */

#endif /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x6bdaae6c, 0x3ad01289),
      TOBN(0x6ad09d91, 0x97a54552),
      TOBN(0x1822bc47, 0xb1e97961),
      0xd4baa4cf,
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {0x6a1fc2eb, 0xd6e24270}
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x29947a69, 0x5f517d15),
      TOBN(0xabc8ff59, 0x31d63f4b),
      TOBN(0x6ad15f7c, 0xd9714856),
      0xb1e97961,
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {UINT64_C(0xd6e242706a1fc2eb), 0}
  };

#endif /* BN_BITS2 */

  static const EC_POINT kGenerator = {
      EC_METHOD_P224,
      STATIC_BIGNUM(kX),
      STATIC_BIGNUM(kY),
      STATIC_BIGNUM(kOne),
  };

  static const EC_GROUP kGroup = {
      EC_METHOD_P224,
      (EC_POINT *)&kGenerator,
      STATIC_BIGNUM(kOrder),
      NID_secp224r1,
      (BN_MONT_CTX *)&kOrderMontgomery,
      STATIC_BIGNUM(kField),
      STATIC_BIGNUM(kA),
      STATIC_BIGNUM(kB),
      1 /* a_is_minus_three */,
#if defined(EC_P224_NO_MONTGOMERY)
      NULL,
#else
      (BN_MONT_CTX *)&kFieldMontgomery,
#endif
      STATIC_BIGNUM(kOne),
  };

  return &kGroup;
}

const EC_GROUP *EC_p256(void) {
  static const BN_ULONG kField[] = {
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0x00000000, 0xffffffff),
      TOBN(0x00000000, 0x00000000),
      TOBN(0xffffffff, 0x00000001),
  };

  static const BN_ULONG kOrder[] = {
      TOBN(0xf3b9cac2, 0xfc632551),
      TOBN(0xbce6faad, 0xa7179e84),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0x00000000),
  };

#if defined(EC_P256_NO_MONTGOMERY)

  static const BN_ULONG kA[] = {
      TOBN(0xffffffff, 0xfffffffc),
      TOBN(0x00000000, 0xffffffff),
      TOBN(0x00000000, 0x00000000),
      TOBN(0xffffffff, 0x00000001),
  };

  static const BN_ULONG kB[] = {
      TOBN(0x3bce3c3e, 0x27d2604b),
      TOBN(0x651d06b0, 0xcc53b0f6),
      TOBN(0xb3ebbd55, 0x769886bc),
      TOBN(0x5ac635d8, 0xaa3a93e7),
  };

  static const BN_ULONG kX[] = {
      TOBN(0xf4a13945, 0xd898c296),
      TOBN(0x77037d81, 0x2deb33a0),
      TOBN(0xf8bce6e5, 0x63a440f2),
      TOBN(0x6b17d1f2, 0xe12c4247),
  };

  static const BN_ULONG kY[] = {
      TOBN(0xcbb64068, 0x37bf51f5),
      TOBN(0x2bce3357, 0x6b315ece),
      TOBN(0x8ee7eb4a, 0x7c0f9e16),
      TOBN(0x4fe342e2, 0xfe1a7f9b),
  };

  static const BN_ULONG kOne[] = {
      0x00000001,
  };

#else /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0x00000000, 0x00000003),
      TOBN(0xfffffffb, 0xffffffff),
      TOBN(0xffffffff, 0xfffffffe),
      TOBN(0x00000004, 0xfffffffd),
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {0x00000001, 0x00000000}
  };

  static const BN_ULONG kA[] = {
      TOBN(0xffffffff, 0xfffffffc),
      TOBN(0x00000003, 0xffffffff),
      TOBN(0x00000000, 0x00000000),
      TOBN(0xfffffffc, 0x00000004),
  };

  static const BN_ULONG kB[] = {
      TOBN(0xd89cdf62, 0x29c4bddf),
      TOBN(0xacf005cd, 0x78843090),
      TOBN(0xe5a220ab, 0xf7212ed6),
      TOBN(0xdc30061d, 0x04874834),
  };

  static const BN_ULONG kX[] = {
      TOBN(0x79e730d4, 0x18a9143c),
      TOBN(0x75ba95fc, 0x5fedb601),
      TOBN(0x79fb732b, 0x77622510),
      TOBN(0x18905f76, 0xa53755c6),
  };

  static const BN_ULONG kY[] = {
      TOBN(0xddf25357, 0xce95560a),
      TOBN(0x8b4ab8e4, 0xba19e45c),
      TOBN(0xd2e88688, 0xdd21f325),
      TOBN(0x8571ff18, 0x25885d85),
  };

  static const BN_ULONG kOne[] = {
      TOBN(0x00000000, 0x00000001),
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xffffffff, 0xffffffff),
      0xfffffffe,
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0x00000000, 0x00000003),
      TOBN(0xfffffffb, 0xffffffff),
      TOBN(0xffffffff, 0xfffffffe),
      TOBN(0x00000004, 0xfffffffd),
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {UINT64_C(0x0000000000000001), 0}
  };

  static const BN_ULONG kA[] = {
      TOBN(0xffffffff, 0xfffffffc),
      TOBN(0x00000003, 0xffffffff),
      TOBN(0x00000000, 0x00000000),
      TOBN(0xfffffffc, 0x00000004),
  };

  static const BN_ULONG kB[] = {
      TOBN(0xd89cdf62, 0x29c4bddf),
      TOBN(0xacf005cd, 0x78843090),
      TOBN(0xe5a220ab, 0xf7212ed6),
      TOBN(0xdc30061d, 0x04874834),
  };

  static const BN_ULONG kX[] = {
      TOBN(0x79e730d4, 0x18a9143c),
      TOBN(0x75ba95fc, 0x5fedb601),
      TOBN(0x79fb732b, 0x77622510),
      TOBN(0x18905f76, 0xa53755c6),
  };

  static const BN_ULONG kY[] = {
      TOBN(0xddf25357, 0xce95560a),
      TOBN(0x8b4ab8e4, 0xba19e45c),
      TOBN(0xd2e88688, 0xdd21f325),
      TOBN(0x8571ff18, 0x25885d85),
  };

  static const BN_ULONG kOne[] = {
      TOBN(0x00000000, 0x00000001),
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xffffffff, 0xffffffff),
      0xfffffffe,
  };

#endif /* BN_BITS2 */

#endif /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x83244c95, 0xbe79eea2),
      TOBN(0x4699799c, 0x49bd6fa6),
      TOBN(0x2845b239, 0x2b6bec59),
      TOBN(0x66e12d94, 0xf3d95620),
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {0xee00bc4f, 0xccd1c8aa}
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x83244c95, 0xbe79eea2),
      TOBN(0x4699799c, 0x49bd6fa6),
      TOBN(0x2845b239, 0x2b6bec59),
      TOBN(0x66e12d94, 0xf3d95620),
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {UINT64_C(0xccd1c8aaee00bc4f), 0}
  };

#endif /* BN_BITS2 */

  static const EC_POINT kGenerator = {
      EC_METHOD_P256,
      STATIC_BIGNUM(kX),
      STATIC_BIGNUM(kY),
      STATIC_BIGNUM(kOne),
  };

  static const EC_GROUP kGroup = {
      EC_METHOD_P256,
      (EC_POINT *)&kGenerator,
      STATIC_BIGNUM(kOrder),
      NID_X9_62_prime256v1,
      (BN_MONT_CTX *)&kOrderMontgomery,
      STATIC_BIGNUM(kField),
      STATIC_BIGNUM(kA),
      STATIC_BIGNUM(kB),
      1 /* a_is_minus_three */,
#if defined(EC_P256_NO_MONTGOMERY)
      NULL,
#else
      (BN_MONT_CTX *)&kFieldMontgomery,
#endif
      STATIC_BIGNUM(kOne),
  };

  return &kGroup;
}

const EC_GROUP *EC_p384(void) {
  static const BN_ULONG kField[] = {
      TOBN(0x00000000, 0xffffffff),
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xffffffff, 0xfffffffe),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
  };

  static const BN_ULONG kOrder[] = {
      TOBN(0xecec196a, 0xccc52973),
      TOBN(0x581a0db2, 0x48b0a77a),
      TOBN(0xc7634d81, 0xf4372ddf),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
  };

#if defined(EC_P384_NO_MONTGOMERY)

  static const BN_ULONG kA[] = {
      TOBN(0x00000000, 0xfffffffc),
      TOBN(0xffffffff, 0x00000000),
      TOBN(0xffffffff, 0xfffffffe),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
  };

  static const BN_ULONG kB[] = {
      TOBN(0x2a85c8ed, 0xd3ec2aef),
      TOBN(0xc656398d, 0x8a2ed19d),
      TOBN(0x0314088f, 0x5013875a),
      TOBN(0x181d9c6e, 0xfe814112),
      TOBN(0x988e056b, 0xe3f82d19),
      TOBN(0xb3312fa7, 0xe23ee7e4),
  };

  static const BN_ULONG kX[] = {
      TOBN(0x3a545e38, 0x72760ab7),
      TOBN(0x5502f25d, 0xbf55296c),
      TOBN(0x59f741e0, 0x82542a38),
      TOBN(0x6e1d3b62, 0x8ba79b98),
      TOBN(0x8eb1c71e, 0xf320ad74),
      TOBN(0xaa87ca22, 0xbe8b0537),
  };

  static const BN_ULONG kY[] = {
      TOBN(0x7a431d7c, 0x90ea0e5f),
      TOBN(0x0a60b1ce, 0x1d7e819d),
      TOBN(0xe9da3113, 0xb5f0b8c0),
      TOBN(0xf8f41dbd, 0x289a147c),
      TOBN(0x5d9e98bf, 0x9292dc29),
      TOBN(0x3617de4a, 0x96262c6f),
  };

  static const BN_ULONG kOne[] = {
      0x00000001,
  };

#else /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0xfffffffe, 0x00000001),
      TOBN(0x00000002, 0x00000000),
      TOBN(0xfffffffe, 0x00000000),
      TOBN(0x00000002, 0x00000000),
      0x00000001,
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {0x00000001, 0x00000001}
  };

  static const BN_ULONG kA[] = {
      TOBN(0x00000003, 0xfffffffc),
      TOBN(0xfffffffc, 0x00000000),
      TOBN(0xffffffff, 0xfffffffb),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
  };

  static const BN_ULONG kB[] = {
      TOBN(0x08118871, 0x9d412dcc),
      TOBN(0xf729add8, 0x7a4c32ec),
      TOBN(0x77f2209b, 0x1920022e),
      TOBN(0xe3374bee, 0x94938ae2),
      TOBN(0xb62b21f4, 0x1f022094),
      TOBN(0xcd08114b, 0x604fbff9),
  };

  static const BN_ULONG kX[] = {
      TOBN(0x3dd07566, 0x49c0b528),
      TOBN(0x20e378e2, 0xa0d6ce38),
      TOBN(0x879c3afc, 0x541b4d6e),
      TOBN(0x64548684, 0x59a30eff),
      TOBN(0x812ff723, 0x614ede2b),
      TOBN(0x4d3aadc2, 0x299e1513),
  };

  static const BN_ULONG kY[] = {
      TOBN(0x23043dad, 0x4b03a4fe),
      TOBN(0xa1bfa8bf, 0x7bb4a9ac),
      TOBN(0x8bade756, 0x2e83b050),
      TOBN(0xc6c35219, 0x68f4ffd9),
      TOBN(0xdd800226, 0x3969a840),
      TOBN(0x2b78abc2, 0x5a15c5e9),
  };

  static const BN_ULONG kOne[] = {
      TOBN(0xffffffff, 0x00000001),
      TOBN(0x00000000, 0xffffffff),
      0x00000001,
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0xfffffffe, 0x00000001),
      TOBN(0x00000002, 0x00000000),
      TOBN(0xfffffffe, 0x00000000),
      TOBN(0x00000002, 0x00000000),
      0x00000001,
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {UINT64_C(0x0000000100000001), 0}
  };

  static const BN_ULONG kA[] = {
      TOBN(0x00000003, 0xfffffffc),
      TOBN(0xfffffffc, 0x00000000),
      TOBN(0xffffffff, 0xfffffffb),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
  };

  static const BN_ULONG kB[] = {
      TOBN(0x08118871, 0x9d412dcc),
      TOBN(0xf729add8, 0x7a4c32ec),
      TOBN(0x77f2209b, 0x1920022e),
      TOBN(0xe3374bee, 0x94938ae2),
      TOBN(0xb62b21f4, 0x1f022094),
      TOBN(0xcd08114b, 0x604fbff9),
  };

  static const BN_ULONG kX[] = {
      TOBN(0x3dd07566, 0x49c0b528),
      TOBN(0x20e378e2, 0xa0d6ce38),
      TOBN(0x879c3afc, 0x541b4d6e),
      TOBN(0x64548684, 0x59a30eff),
      TOBN(0x812ff723, 0x614ede2b),
      TOBN(0x4d3aadc2, 0x299e1513),
  };

  static const BN_ULONG kY[] = {
      TOBN(0x23043dad, 0x4b03a4fe),
      TOBN(0xa1bfa8bf, 0x7bb4a9ac),
      TOBN(0x8bade756, 0x2e83b050),
      TOBN(0xc6c35219, 0x68f4ffd9),
      TOBN(0xdd800226, 0x3969a840),
      TOBN(0x2b78abc2, 0x5a15c5e9),
  };

  static const BN_ULONG kOne[] = {
      TOBN(0xffffffff, 0x00000001),
      TOBN(0x00000000, 0xffffffff),
      0x00000001,
  };

#endif /* BN_BITS2 */

#endif /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x2d319b24, 0x19b409a9),
      TOBN(0xff3d81e5, 0xdf1aa419),
      TOBN(0xbc3e483a, 0xfcb82947),
      TOBN(0xd40d4917, 0x4aab1cc5),
      TOBN(0x3fb05b7a, 0x28266895),
      TOBN(0x0c84ee01, 0x2b39bf21),
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {0xe88fdc45, 0x6ed46089}
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x2d319b24, 0x19b409a9),
      TOBN(0xff3d81e5, 0xdf1aa419),
      TOBN(0xbc3e483a, 0xfcb82947),
      TOBN(0xd40d4917, 0x4aab1cc5),
      TOBN(0x3fb05b7a, 0x28266895),
      TOBN(0x0c84ee01, 0x2b39bf21),
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {UINT64_C(0x6ed46089e88fdc45), 0}
  };

#endif /* BN_BITS2 */

  static const EC_POINT kGenerator = {
      EC_METHOD_P384,
      STATIC_BIGNUM(kX),
      STATIC_BIGNUM(kY),
      STATIC_BIGNUM(kOne),
  };

  static const EC_GROUP kGroup = {
      EC_METHOD_P384,
      (EC_POINT *)&kGenerator,
      STATIC_BIGNUM(kOrder),
      NID_secp384r1,
      (BN_MONT_CTX *)&kOrderMontgomery,
      STATIC_BIGNUM(kField),
      STATIC_BIGNUM(kA),
      STATIC_BIGNUM(kB),
      1 /* a_is_minus_three */,
#if defined(EC_P384_NO_MONTGOMERY)
      NULL,
#else
      (BN_MONT_CTX *)&kFieldMontgomery,
#endif
      STATIC_BIGNUM(kOne),
  };

  return &kGroup;
}

const EC_GROUP *EC_p521(void) {
  static const BN_ULONG kField[] = {
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      0x000001ff,
  };

  static const BN_ULONG kOrder[] = {
      TOBN(0xbb6fb71e, 0x91386409),
      TOBN(0x3bb5c9b8, 0x899c47ae),
      TOBN(0x7fcc0148, 0xf709a5d0),
      TOBN(0x51868783, 0xbf2f966b),
      TOBN(0xffffffff, 0xfffffffa),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      0x000001ff,
  };

#if defined(EC_P521_NO_MONTGOMERY)

  static const BN_ULONG kA[] = {
      TOBN(0xffffffff, 0xfffffffc),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      0x000001ff,
  };

  static const BN_ULONG kB[] = {
      TOBN(0xef451fd4, 0x6b503f00),
      TOBN(0x3573df88, 0x3d2c34f1),
      TOBN(0x1652c0bd, 0x3bb1bf07),
      TOBN(0x56193951, 0xec7e937b),
      TOBN(0xb8b48991, 0x8ef109e1),
      TOBN(0xa2da725b, 0x99b315f3),
      TOBN(0x929a21a0, 0xb68540ee),
      TOBN(0x953eb961, 0x8e1c9a1f),
      0x00000051,
  };

  static const BN_ULONG kX[] = {
      TOBN(0xf97e7e31, 0xc2e5bd66),
      TOBN(0x3348b3c1, 0x856a429b),
      TOBN(0xfe1dc127, 0xa2ffa8de),
      TOBN(0xa14b5e77, 0xefe75928),
      TOBN(0xf828af60, 0x6b4d3dba),
      TOBN(0x9c648139, 0x053fb521),
      TOBN(0x9e3ecb66, 0x2395b442),
      TOBN(0x858e06b7, 0x0404e9cd),
      0x000000c6,
  };

  static const BN_ULONG kY[] = {
      TOBN(0x88be9476, 0x9fd16650),
      TOBN(0x353c7086, 0xa272c240),
      TOBN(0xc550b901, 0x3fad0761),
      TOBN(0x97ee7299, 0x5ef42640),
      TOBN(0x17afbd17, 0x273e662c),
      TOBN(0x98f54449, 0x579b4468),
      TOBN(0x5c8a5fb4, 0x2c7d1bd9),
      TOBN(0x39296a78, 0x9a3bc004),
      0x00000118,
  };

  static const BN_ULONG kOne[] = {
      0x00000001,
  };

#else /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0x00004000, 0x00000000),
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {0x00000001, 0x00000000}
  };

  static const BN_ULONG kA[] = {
      TOBN(0xffffffff, 0xfe7fffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      0x000001ff,
  };

  static const BN_ULONG kB[] = {
      TOBN(0xea35a81f, 0x8014654f),
      TOBN(0xc41e961a, 0x78f7a28f),
      TOBN(0x5e9dd8df, 0x839ab9ef),
      TOBN(0xa8f63f49, 0xbd8b2960),
      TOBN(0xc8c77884, 0xf0ab0c9c),
      TOBN(0x2dccd98a, 0xf9dc5a44),
      TOBN(0xd05b42a0, 0x77516d39),
      TOBN(0xb0c70e4d, 0x0fc94d10),
      0x0000015c,
  };

  static const BN_ULONG kX[] = {
      TOBN(0x18e172de, 0xb331a163),
      TOBN(0xe0c2b521, 0x4dfcbf3f),
      TOBN(0x93d17fd4, 0x6f19a459),
      TOBN(0x3bf7f3ac, 0x947f0ee0),
      TOBN(0xb035a69e, 0xdd50a5af),
      TOBN(0x9c829fda, 0x90fc1457),
      TOBN(0xb311cada, 0x214e3240),
      TOBN(0x5b820274, 0xe6cf1f65),
      0x00000103,
  };

  static const BN_ULONG kY[] = {
      TOBN(0x3b4fe8b3, 0x28460e4a),
      TOBN(0x43513961, 0x20445f4a),
      TOBN(0x809fd683, 0xb09a9e38),
      TOBN(0x4caf7a13, 0x2062a85c),
      TOBN(0x8b939f33, 0x164bf739),
      TOBN(0x24abcda2, 0x340bd7de),
      TOBN(0xda163e8d, 0xeccc7aa2),
      TOBN(0x3c4d1de0, 0x022e452f),
      0x000000b5,
  };

  static const BN_ULONG kOne[] = {
      0x00800000,
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kFieldMontgomeryR2[] = {
      TOBN(0x00000000, 0x00000000),
      TOBN(0x00004000, 0x00000000),
  };

  static const BN_MONT_CTX kFieldMontgomery = {
      STATIC_BIGNUM(kFieldMontgomeryR2),
      STATIC_BIGNUM(kField),
      {UINT64_C(0x0000000000000001), 0}
  };

  static const BN_ULONG kA[] = {
      TOBN(0xfe7fffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      TOBN(0xffffffff, 0xffffffff),
      0x000001ff,
  };

  static const BN_ULONG kB[] = {
      TOBN(0x8014654f, 0xae586387),
      TOBN(0x78f7a28f, 0xea35a81f),
      TOBN(0x839ab9ef, 0xc41e961a),
      TOBN(0xbd8b2960, 0x5e9dd8df),
      TOBN(0xf0ab0c9c, 0xa8f63f49),
      TOBN(0xf9dc5a44, 0xc8c77884),
      TOBN(0x77516d39, 0x2dccd98a),
      TOBN(0x0fc94d10, 0xd05b42a0),
      0x0000004d,
  };

  static const BN_ULONG kX[] = {
      TOBN(0xb331a163, 0x81adc101),
      TOBN(0x4dfcbf3f, 0x18e172de),
      TOBN(0x6f19a459, 0xe0c2b521),
      TOBN(0x947f0ee0, 0x93d17fd4),
      TOBN(0xdd50a5af, 0x3bf7f3ac),
      TOBN(0x90fc1457, 0xb035a69e),
      TOBN(0x214e3240, 0x9c829fda),
      TOBN(0xe6cf1f65, 0xb311cada),
      0x00000074,
  };

  static const BN_ULONG kY[] = {
      TOBN(0x28460e4a, 0x5a9e268e),
      TOBN(0x20445f4a, 0x3b4fe8b3),
      TOBN(0xb09a9e38, 0x43513961),
      TOBN(0x2062a85c, 0x809fd683),
      TOBN(0x164bf739, 0x4caf7a13),
      TOBN(0x340bd7de, 0x8b939f33),
      TOBN(0xeccc7aa2, 0x24abcda2),
      TOBN(0x022e452f, 0xda163e8d),
      0x000001e0,
  };

  static const BN_ULONG kOne[] = {
      TOBN(0x00800000, 0x00000000),
  };

#endif /* BN_BITS2 */

#endif /* NO_MONTGOMERY */

#if BN_BITS2 == 32

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x1163115a, 0x61c64ca7),
      TOBN(0x18354a56, 0x4374a642),
      TOBN(0x5d4dd6d3, 0x0791d9dc),
      TOBN(0x4fb35b72, 0xd3402705),
      TOBN(0xcff3d142, 0xb7756e3a),
      TOBN(0x5bcc6d61, 0xa8e567bc),
      TOBN(0x2d8e03d1, 0x492d0d45),
      TOBN(0x5b5a3afe, 0x8c44383d),
      0x0000019a,
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {0x79a995c7, 0x1d2f5ccd}
  };

#elif BN_BITS2 == 64

  static const BN_ULONG kOrderMontgomeryR2[] = {
      TOBN(0x137cd04d, 0xcf15dd04),
      TOBN(0xf707badc, 0xe5547ea3),
      TOBN(0x12a78d38, 0x794573ff),
      TOBN(0xd3721ef5, 0x57f75e06),
      TOBN(0xdd6e23d8, 0x2e49c7db),
      TOBN(0xcff3d142, 0xb7756e3e),
      TOBN(0x5bcc6d61, 0xa8e567bc),
      TOBN(0x2d8e03d1, 0x492d0d45),
      0x0000003d,
  };

  static const BN_MONT_CTX kOrderMontgomery = {
      STATIC_BIGNUM(kOrderMontgomeryR2),
      STATIC_BIGNUM(kOrder),
      {UINT64_C(0x1d2f5ccd79a995c7), 0}
  };

#endif /* BN_BITS2 */

  static const EC_POINT kGenerator = {
      EC_METHOD_P521,
      STATIC_BIGNUM(kX),
      STATIC_BIGNUM(kY),
      STATIC_BIGNUM(kOne),
  };

  static const EC_GROUP kGroup = {
      EC_METHOD_P521,
      (EC_POINT *)&kGenerator,
      STATIC_BIGNUM(kOrder),
      NID_secp521r1,
      (BN_MONT_CTX *)&kOrderMontgomery,
      STATIC_BIGNUM(kField),
      STATIC_BIGNUM(kA),
      STATIC_BIGNUM(kB),
      1 /* a_is_minus_three */,
#if defined(EC_P521_NO_MONTGOMERY)
      NULL,
#else
      (BN_MONT_CTX *)&kFieldMontgomery,
#endif
      STATIC_BIGNUM(kOne),
  };

  return &kGroup;
}

